# config/cucumber.yml
##YAML Template

ios: -f 'Slowhandcuke::Formatter' PLATFORM=ios -r features/support -r features/ios/ -r features/ios/support -r features/ios/helpers -r features/step_definitions -r features/ios/pages -f html -o ios-report.html -f junit -o features/report/junit -f json -o features/report/ios-report.json
android: -f 'Slowhandcuke::Formatter' PLATFORM=android -r features/support -r features/android/ -r features/android/support -r features/android/helpers -r features/step_definitions -r features/android/pages -f html -o android-report.html -f junit -o features/report/junit -f json -o features/report/android-report.json
